integrations:
  gcl:
    type: dataset
    ref: paperspace/ds7me5hgjbfht6q:8ngwr2a
  poplar-executables-pytorch-3-3:
    type: dataset
    ref: paperspace/dsh5zgn2rclo0xr:69dlze7
  ogbl_wikikg2_custom:
    type: dataset
    ref: paperspace/ds5fogtxxi0h935:wqp02u5
  chest-xray-nihcc-3:
    type: dataset
    ref: paperspace/dsfzugibmi3rtyo:1mq8ehu
