# Copyright (c) 2022 Graphcore Ltd. All rights reserved.

_common_source_repository: &_common_source_repository
  origin: examples-internal/
  ref: null

_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

gptj:
  source:
    paths:
    - expression: '*'
      path: nlp/gpt_j/popxl
      recursive: true
    excludes:
    - path: nlp/gpt_j/popxl/README.md
    - path: nlp/gpt_j/popxl/.gitignore
    repository:
      <<: *_common_source_repository
      prefix: nlp/gpt_j/popxl
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: gptj-text-generation

tgn:
  source:
    paths:
    - expression: '*'
      path: gnn/tgn/pytorch
      recursive: true
    excludes:
    - path: gnn/tgn/pytorch/README.md
    - path: gnn/tgn/pytorch/.gitignore
    - expression: '*'
      path: gnn/tgn/pytorch/.ci
      recursive: true
    repository:
      <<: *_common_source_repository
      prefix: gnn/tgn/pytorch
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: temporal-graph-networks

distributed-kge-pytorch:
  source:
    paths:
    - expression: '*'
      path: doc/pytorch_demo
      recursive: true
    excludes:
    - path: doc/pytorch_demo/README.md
    repository:
      origin: https://github.com/graphcore/distributed-kge-poplar
      ref: main
      prefix: doc/pytorch_demo
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: distributed-kge

# Not ready
# gpt2-inference:
#   source:
#     paths:
#     - expression: '*'
#       path: nlp/gpt2/pytorch
#       recursive: true
#     excludes:
#     - expression: '*'
#       path: nlp/gpt2/pytorch/.ci
#       recursive: true
#     repository:
#       origin: git@github.com:graphcore/examples-internal.git
#       ref: gpt2_inference_notebook
#       prefix: nlp/gpt2/pytorch
#   target:
#     renames: {}
#     repository:
#       <<: *_common_target_repository
#       prefix: gpt2-text-generation
#


pytorch-finetuning-bert:
  source:
    paths:
    - expression: '*'
      path: tutorials/tutorials/pytorch/finetuning_bert
      recursive: true
    excludes:
    - path: tutorials/tutorials/pytorch/finetuning_bert/tests
    - path: tutorials/tutorials/pytorch/finetuning_bert/Fine-tuning-BERT.py
    - path: tutorials/tutorials/pytorch/finetuning_bert/README.md
    - expression: '*'
      path: tutorials/tutorials/pytorch/finetuning_bert/.ci
      recursive: true
    repository:
      <<: *_common_source_repository
      prefix: tutorials/tutorials/pytorch/finetuning_bert
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: finetuning-bert



pytorch-vit-finetuning:
  source:
    paths:
    - expression: '*'
      path: tutorials/tutorials/pytorch/vit_model_training
      recursive: true
    excludes:
    - path: tutorials/tutorials/pytorch/vit_model_training/README.md
    - expression: '*'
      path: tutorials/tutorials/pytorch/vit_model_training/.ci
      recursive: true
    - expression: '*'
      path: tutorials/tutorials/pytorch/vit_model_training/tests
      recursive: true
    repository:
      <<: *_common_source_repository
      prefix: tutorials/tutorials/pytorch/vit_model_training
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: vit-model-training


pytorch-basics:
  source:
    paths:
    - expression: '*'
      path: tutorials/tutorials/pytorch/basics
      recursive: true
    excludes:
    - path: tutorials/tutorials/pytorch/basics/README.md
    - expression: '*'
      path: tutorials/tutorials/pytorch/basics/.ci
      recursive: true
    - expression: '*'
      path: tutorials/tutorials/pytorch/basics/tests
      recursive: true
    repository:
      <<: *_common_source_repository
      prefix: tutorials/tutorials/pytorch/basics
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-PyTorch-on-IPU/basics

pytorch-efficient-dataloading:
  source:
    paths:
    - expression: '*'
      path: tutorials/tutorials/pytorch/efficient_data_loading
      recursive: true
    excludes:
    - path: tutorials/tutorials/pytorch/efficient_data_loading/README.md
    - expression: '*'
      path: tutorials/tutorials/pytorch/efficient_data_loading/.ci
      recursive: true
    - expression: '*'
      path: tutorials/tutorials/pytorch/efficient_data_loading/tests
      recursive: true
    repository:
      <<: *_common_source_repository
      prefix: tutorials/tutorials/pytorch/efficient_data_loading
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-PyTorch-on-IPU/efficient_data_loading

pytorch-efficient-mixed-precision:
  source:
    paths:
    - expression: '*'
      path: tutorials/tutorials/pytorch/mixed_precision
      recursive: true
    excludes:
    - path: tutorials/tutorials/pytorch/mixed_precision/README.md
    - expression: '*'
      path: tutorials/tutorials/pytorch/mixed_precision/.ci
      recursive: true
    - expression: '*'
      path: tutorials/tutorials/pytorch/mixed_precision/tests
      recursive: true
    repository:
      <<: *_common_source_repository
      prefix: tutorials/tutorials/pytorch/mixed_precision
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-PyTorch-on-IPU/mixed_precision

pytorch-efficient-pipelining:
  source:
    paths:
    - expression: '*'
      path: tutorials/tutorials/pytorch/pipelining
      recursive: true
    excludes:
    - path: tutorials/tutorials/pytorch/pipelining/README.md
    - expression: '*'
      path: tutorials/tutorials/pytorch/pipelining/.ci
      recursive: true
    - expression: '*'
      path: tutorials/tutorials/pytorch/pipelining/tests
      recursive: true
    repository:
      <<: *_common_source_repository
      prefix: tutorials/tutorials/pytorch/pipelining
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: learning-PyTorch-on-IPU/pipelining

managing_ipu_resources:
  source:
    paths:
    - path: notebooks/managing_ipu_resources.ipynb
    repository:
      origin: git@github.com:graphcore/optimum-graphcore-fork.git
      ref: main
      prefix: notebooks/
  target:
    renames: {}
    repository:
      <<: *_common_target_repository
      prefix: useful-tips/

yolov4-object-detection:
    source:
      paths:
      - expression: '*'
        path: vision/yolo_v4/pytorch
        recursive: true
      repository:
        origin: examples-internal/
        ref: yolo-notebook
        prefix: vision/yolo_v4/pytorch
      excludes:
        - path: vision/yolo_v4/pytorch/.ci/
        - path: vision/yolo_v4/pytorch/conftest.py
        - path: vision/yolo_v4/pytorch/tests/
        - path: vision/yolo_v4/pytorch/README.md
    target:
      renames: {}
      repository:
        <<: *_common_source_repository
        prefix: object-detection-with-yolo