

_current_repo_in_github_actions: &_current_repo_in_github_actions
    origin: notebooks/
    ref: null

almost-scaled:
  source:
    paths:
    - expression: '*'
      path: analysis/almost_scaled_dot_product_attention
      recursive: true
    repository:
      origin: https://github.com/graphcore-research/unit-scaling.git
      ref: main
      prefix: analysis/almost_scaled_dot_product_attention
  target:
    renames: {}
    repository:
      <<: *_current_repo_in_github_actions
      prefix: almost_scaled_dot_product_attention
